### PR TITLE
Support external libs

### PR DESCRIPTION
**Pull request by bobbicodes**
This PR adds support for transitive hot-loading of dependencies found in `project.clj` via this experimental alpha-feature: https://github.com/clojure/tools.deps.alpha/tree/add-lib3

Note: The reason this has gotten so complicated is due to Clojure's highly dynamic nature. It is not technically possible to statically determine whether a variable is in a thread-local context, so in order to remove any chance of replacing names that we shouldn't, we actually need to evaluate everything.

[Don't take my word for it](https://github.com/clojure/tools.analyzer/blob/fd55a292ff4802bd7b7e8b78036d0d1e25f6e48b/src/main/clojure/clojure/tools/analyzer.clj#L247)

EDIT: Indeed, as I've learned more recently, without evaluating the code we are not even able to perform macroexpansion, making it impossible to normalize say, this:

``` clojure
(defn foo [x]
  (str x))
```

and this, which is functionally identical:

``` clojure
(def foo (fn [x]
  (str x)))
```

Or this:

``` clojure
(when true
  true))
```

and this:

``` clojure
(if true 
  (do true))
```

### CODE REVIEW

**Comment by bobbicodes** [comment]
I might be experiencing what ought to be called the "Classpath Blues", which is giving me some valuable education but is also contributing to a nagging feeling that I may be over-engineering this thing.

Classpaths are an incredibly complicated beast in Clojure, which goes to outstanding lengths to create a dynamic environment on the JVM. Right now I'm having issues with the `add-libs` functionality (we must remember that it is Alpha and thus very experimental) and I'm concerned that I might be venturing outside of its intended use.

To be specific, it works great in development but fails in testing for some reason. To be even more specific, it throws an [IllegalAccessError](https://github.com/clojure/tools.deps.alpha/blob/8f8fc2571e721301b6d52e191129248355cb8c5a/src/main/clojure/clojure/tools/deps/alpha/repl.clj#L73) because apparently the _Context Classloader_ is not a _DynamicClassloader_. I do not claim to understand what that means. These tools are very sharp and might best be removed from my reach or someone could get hurt.

For a wonderfully detailed explanation of classpaths in Clojure, including this perplexing DynamicClassloader business, see Arne's blog post: https://lambdaisland.com/blog/2021-08-25-classpath-is-a-lie

clj-kondo manages to figure out, with a reasonable (though not 100% bulletproof) degree of confidence whether a variable is user-defined or not, without ever running any code. As far as I can tell it does this by keeping track of scope and maintaining a quite amusing (you guessed it) [exhaustive list of core symbol names](https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/var_info_gen.clj). And if it's good enough for the community's most accepted linter, it's likely good enough for us.

I might re-evaluate this (pun intended). The appropriate design decision for this problem space could very well be to accept that sometimes, in certain rare edge cases, it may be wrong.

**Comment by ErikSchierboom** [comment]
@BTowersCoding Let me know when you'd like me to review

**Comment by bobbicodes** [comment]
I just thought of an idea. [Eastwood](https://github.com/jonase/eastwood) is a Clojure lint tool that is based on `tools.analyzer`. Because of this it is much more powerful and accurate than `clj-kondo` - the downside is that, being hosted on the JVM, it is much slower, making it impractical for things like using it inside text editors.

However, our use case happens to be more analogous to linting in CI, which is where Eastwood excels greatly.

I discovered it because it turns out that it actually powers clj-kondo's ability to detect whether a var is a Clojure symbol or a local (the file linked in the comment above containing the symbol names is extracted from eastwood). I bet I can study it to figure out how to solve the problem that has gotten me stuck here, regarding how to analyze code containing external libraries.

EDIT: Reading the source for eastwood, this stuff is so good it's probably worth actually using it directly!

As described [here](https://github.com/jonase/eastwood#usage-1), the `:compare-forms` option may be particularly useful for us:

> :compare-forms - print all forms as read to a file forms-read.txt, all forms after being analyzed to a file forms-analyzed.txt, and all forms after being read, analyzed into an AST, and converted back into a form from the AST, to a file forms-emitted.txt.

We could actually do this, then run the result _back_ through my [hacked version](https://github.com/exercism/clojure-representer/blob/1c3e3b1556eddd3820838c3a464fa43dc90bf258/src/clojure_representer/analyzer/passes/uniquify.clj#L24) of `tools.analyzer` which replaces the variable names according to the representer spec, and we're done! I'm confident that this would create the most accurate, bulletproof representer possible.

**Comment by bobbicodes** [comment]
EDIT: most of this comment is outdated because it was written before the above "revelation", but it shall be retained for comedic effect

It could be I'm simply thinking about this wrong...

What if... this whole business with `add-libs` is not necessary and I've been needlessly complicating it this whole time?

That would indeed be pretty silly. But entirely believable, since I never at any point in this have actually known what I'm doing. This is what happens when you send a beginner to do a real tooling author's job. But nobody started out knowing what they're doing.

Except for [Lars](https://www.youtube.com/watch?v=dIVSceUm69s). He always knew everything.

Are you ready for this?

How about...

...Instead of running the solution inside the representer... get this...

...am I building up enough suspense?

We run the representer *inside the solution*.

This isn't actually as profound as it might sound, it's actually pretty embarrassing. And now in retrospect I kind of recall *almost* figuring it out at a couple of points only to second guess myself and then think "yeah, I guess it really has to be loaded at runtime and there's no way around that, nope nope nope". Whoever is reading this, maybe don't tell anyone it took me this long to figure out? OK so it goes like this:

The solution is a complete project. It contains everything needed to... well wait a minute... it would have to already have all its dependencies, because the container doesn't have network access.

Could I just hack around this by including local versions of every library likely to be used? This is not even anything special, really. On my system, for example, Maven artifacts are stored in a local cache folder called `.m2`, and part of the dependency resolution strategy is to look there first before attempting to download anything.

Clojure builds are often even simpler though, because many libraries are designed to run from source code without even needing any preparation :) Usually these are downloaded straight from GitHub (i.e. [gitlibs](https://clojure.org/reference/deps_and_cli#_git)) by providing a sha (this can be any commit from a repo, a gist (which can also include multiple files), or... get ready for this... even a [tweet](https://github.com/vlaaad/tweet-def), or [anywhere else on the internet](https://github.com/tonsky/remote-require)!), but can easily be overridden in the config to be pulled from a local folder. See: https://clojure.org/reference/deps_and_cli#_dependencies

FWIW, the entire online editor experience is a closed system. Students can't use anything that we didn't specifically put in the test runner (though I've made an effort to respond to community requests for popular libraries to [be included via a Java Archive](https://github.com/exercism/clojure-test-runner/blob/5d243166bea1d82072eb592c9c3ccbd9500d8164/test-runner.clj#L9)). So I might be making way more of a doozy* out of this than need be.

> \* doo·zy
> noun INFORMAL • NORTH AMERICAN
> something outstanding or unique of its kind.
> "it's gonna be a doozy of a black eye"

And if a solution uses some weird library that we've never seen before, that's unique enough to get a special pass!

The representer could just have a check where it would say "Ding ding ding! You win! You just used `joe-shmo's-awesome-obscure-library` and we've never seen that before!

**Comment by bobbicodes** [comment]
Successfully generates representations for 500 solutions to `armstrong-numbers`.

Was slightly anticlimactic because there are still 479 unique solutions, so there is still more work to be done. Specifically, top-level (global) function names are still left as they are because so far we're only replacing local identifiers, but this doesn't take into account the numerous intermediate functions commonly written for things like exponentiation and splitting a number into digits. 

It would also be good to remove much of the redundancy, because the representations, while extremely accurate, contain a lot of stuff that doesn't need to be in there and is pretty much the same in each one.

However, this is a good time to merge I think because the architecture is sound, tests are green and we're properly handling solutions using the `math.numeric-tower` library.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> Was slightly anticlimactic because there are still 479 unique solutions, so there is still more work to be done. 

Yeah, I know the feeling. Incremental improvements will help.

**Pull request merged**
