### PR TITLE
Massively simplified representer

### PR DESCRIPTION
**Pull request by bobbicodes**
The Representer-lite (https://github.com/exercism/clojure-representer/pull/38) was the result of replacing clojure.tools.analyzer with static analysis data gathered by shelling out to clj-kondo.

This version eliminates the need for clj-kondo by accomplishing the same thing itself. All we were actually using it for was to determine which symbols to replace.

I extracted the set of clojure core symbols from [here](https://github.com/clj-kondo/clj-kondo/blob/e0a3d10022bf08bf5055eca41304fdc353fed2a9/src/clj_kondo/impl/var_info_gen.clj). We simply walk the data structure of the macroexpanded source code and gather all the symbols and eliminate the ones that are core symbols, as well as taking the difference of the remaining symbols and the symbols contained in the test suite. This kind of magically did the trick, because it ensures that the functions that are tested are left, i.e. not replaced with placeholders.

Then I realized we no longer needed the whole extra step of replacing the `def`s, because they are also symbols. So half the code (and the need to ship an entire binary) ended up disappearing!

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@bobbicodes Should I still review https://github.com/exercism/clojure-representer/pull/38 or does this supersede that PR?

**Comment by bobbicodes** [comment]
We could probably just wait until this one is ready

**Comment by bobbicodes** [comment]
Still chasing a couple of bugs that were revealed once I tested 1000 solutions. Some more things need to be normalized (objects with hashes that are different each time).

I'm trying to clean them with regexes, but it's not working and it's making me question my entire reality.


Here is my `clean` function:

```clojure
(defn clean
  "Macroexpansion of destructuring bindings result in objects like this:
   #object[clojure.core$nth 0x94442d9 \"clojure.core$nth@94442d9\"].
   This normalizes them."
  [s]
  (-> s
      (str/replace #"nth\s0x\w+" "nth")
      (str/replace #"seq\s0x\w+" "seq")
      (str/replace #"seq@\w+" "seq")
      (str/replace #"seq__\w+" "seq")
      (str/replace #"seq__\w+@\w+" "seq")
      (str/replace #"nth@\w+" "nth")))
```

Here's where is appears in the representation (condensed for brevity):

`" . . . #object[clojure.core$seq__5467 0x43edf199 \"clojure.core$seq__5467@43edf199\"] . . ."`

And here it is, processed by `clean`:

`#object[clojure.core$seq \"clojure.core$seq\"]`

Which is correct! The function works as expected. I don't get it.

It seems fail because it's running it through a series of replacements. But I don't see why that should matter... but perhaps it will work if I combine it into a single regex...

ok hahaha I think this is a classic example of regexes not composing. It's like that awful "joke". Almost fixed.

**Comment by bobbicodes** [comment]
Oh, I see what it was doing. The last commit (which made CI pass) differed only in the placeholder numbers. So it seems that the ordering of the placeholders is nondeterministic. I might need to sort them.

**Comment by bobbicodes** [comment]
Wait.... that doesn't seem right... no, there's no possible way the order could change. It just looks each symbol up in a map as it walks the code, replacing it if it exists.

**Review by ErikSchierboom — APPROVED** [review]
It's hard to review this with the many changed files, but CI is green 🤷

**Pull request merged**
