### PR TITLE
Representer lite

### PR DESCRIPTION
**Pull request by bobbicodes**
Removes dependency on clojure.tools.analyzer. Runs with babashka for instantaneous startup.

Something strange is happening, the tests pass on my machine but these 2 tests fail in CI and I can't figure it out

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> Something strange is happening, the tests pass on my machine but these 2 tests fail in CI and I can't figure it out

I get the same errors on my machine when running `./bin/run-tests-in-docker.sh`

**Comment by bobbicodes** [comment]
I removed Docker from my machine because I don't have the space for it... but I just ordered an external hard drive which will be here next week

Update: It arrives tomorrow!

**Comment by bobbicodes** [comment]
I want to clean up the code substantially. It's traversing the code like 4 different ways, a confusing combination of zippers, reducing functions and tree walking, and I'm thinking that the tree walking functions could be generalized across everything, which would result in both cleaner abstractions and improved performance.

This is basically the same approach that [clojure.tools.analyzer](https://github.com/clojure/tools.analyzer/blob/master/src/main/clojure/clojure/tools/analyzer/ast.clj) uses, but we're not walking an AST, rather the code forms themselves as generic data structures, as in [clojure.walk](https://github.com/clojure/clojure/blob/master/src/clj/clojure/walk.clj).

Another option could be to take after [clj-kondo](https://github.com/clj-kondo/clj-kondo/blob/master/parser/clj_kondo/impl/rewrite_clj/parser.clj), which parses rewrite-clj nodes, without using zippers. I'll play around with these ideas and see what works best.

**Comment by bobbicodes** [comment]
This is pretty cool... we perform static analysis with clj-kondo, and it's cross platform:

```clojure
(defn analyze [f]
  (let [bin (if (try (shell/sh "ls") (catch Exception e false))
                   "./clj-kondo" "./clj-kondo.exe")
        cmd [bin "--lint" (str f) "--config"
             "{:output {:format :edn},:analysis {:locals true :arglists true}}"]]
    (:analysis (edn/read-string (:out (apply shell/sh cmd))))))
```

It simply tries running `ls`. If it succeeds the binary is `clj-kondo`, otherwise it's `clj-kondo.exe`. Tested on native Windows and Ubuntu WSL2.

~~Somewhat surprisingly, this call to `io/file` produces a cross-platform path:
`(io/file "resources\\armstrong_numbers\\0\\src\\armstrong_numbers.clj")`~~

EDIT: actually no, it doesn't.

This does:

```clojure
(def f (io/file "resources" "armstrong_numbers"
                "0" "src" "armstrong_numbers.clj"))
```

This analysis step is necessary to inform us which identifiers are locals and which ones are symbols from clojure.core. This is critical because the locals need to be normalized, but clojure symbols are not. clj-kondo determines this statically by [generating an exhaustive list](https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/var_info_gen.clj) from the [Eastwood linter's var-info.edn](https://github.com/jonase/eastwood/blob/master/resource/var-info.edn).

Perhaps we could do something similar here by importing the var-info and checking the symbols ourselves, and eliminate the need for static analysis at all?

**Comment by bobbicodes** [comment]
Yay! It works

Er... wait... still not quite right. I need to figure out how I want it to work in dev vs. production. I think the last commit passed CI because it was just analyzing the same test file 100 times

**Comment by bobbicodes** [comment]
Now it's erroring with `Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.`.

But I'm confused... because we're no longer using Java. Where is that being called from? I have no idea.

The good news is... it tests 100 solutions in 5.664 seconds. And the code is cleaner than it's ever been.

I'm suspecting it's something to do with Docker. I'll be able to debug later.

**Comment by bobbicodes** [comment]
And it's green! It seems that the Java problem above was due to `bb.edn` (config for babashka project), so I refactored the program to not use it.

I think the last thing I have to do is modify `run.sh` to call the representer cli the right way in production.

**Pull request closed without merging**
